### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by MorningLightMountain713** [vojtechtrefny/pyblkid#15]
I run the example and I get keyerror for usage.

I want to be able to find a device by label.

Basically:

``` bash

blkid --label <my label>
/dev/mydevice
```

**Comment by vojtechtrefny** [comment]
For that you need to use the [cache](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.40/libblkid-docs/libblkid-Cache.html) API:

```
In [1]: import blkid

In [2]: cache = blkid.Cache()

In [3]: cache.probe_all()

In [4]: dev = cache.find_device("LABEL", "mylabel")

In [5]: dev.devname
Out[5]: '/dev/loop0'

In [6]: dev.tags
Out[6]: 
{'LABEL': 'mylabel',
 'UUID': '82ce617f-7b27-4b33-8cb9-e55b17e026ec',
 'BLOCK_SIZE': '1024',
 'TYPE': 'ext4'}

**Comment by vojtechtrefny** [comment]
I've also updated the README file with this example. I am closing this issue now, feel free to reopen it if you have further questions.

**Comment by MorningLightMountain713** [comment]
Thank you very much - working as described.
